name: quranapps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  lottie: ^2.4.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  get: any
  get_cli: ^1.8.1
  get_storage: 2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

